[versions]
activity-compose = "1.9.3"
coil = "2.7.0"
compose = "1.7.5"
compose-material = "1.7.5"
compose-material3 = "1.3.1"
compose-navigation = "2.8.4"
core = "1.15.0"
core-splashscreen = "1.0.1"
fuzzywuzzy = "1.4.0"
junit-jupiter = "5.11.3"
kotlinx-serialization-json = "1.8.0"
lifecycle-runtime = "2.8.7"
media = "1.7.0"
okhttp3 = "4.12.0"
room = "2.6.1"

android-gradle-plugin = "8.7.3"
kotlin-gradle-plugin = "2.1.0"
kotlin-serialization-plugin = "2.1.0"
ksp-plugin = "2.1.0-1.0.29"

compile-sdk = "35"
min-sdk = "28"
target-sdk = "34"
junit = "4.13.2"
junit-version = "1.2.1"
espresso-core = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"

[libraries]
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
coil = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "compose-material" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "compose-material3" }
compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "compose-navigation" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "compose" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
core = { group = "androidx.core", name = "core-ktx", version.ref = "core" }
core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "core-splashscreen" }
fuzzywuzzy = { group = "me.xdrop", name = "fuzzywuzzy", version.ref = "fuzzywuzzy" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit-jupiter" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime" }
media = { group = "androidx.media", name = "media", version.ref = "media" }
okhttp3 = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp3" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit-version" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-app = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-gradle-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin-gradle-plugin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-serialization-plugin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp-plugin" }
room = { id = "androidx.room", version.ref = "room" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
