[versions]
activity-compose = "1.8.2"
coil = "2.6.0"
compose = "1.6.6"
compose-compiler = "1.5.12"
compose-material = "1.6.6"
compose-material3 = "1.3.0-alpha05"
compose-navigation = "2.7.7"
core = "1.13.0"
core-splashscreen = "1.0.1"
fuzzywuzzy = "1.4.0"
jaudiotagger = "3.0.1"
lifecycle-runtime = "2.7.0"
media = "1.7.0"
okhttp3 = "4.12.0"

android-gradle-plugin = "8.3.2"
kotlin-gradle-plugin = "1.9.23"

compile-sdk = "34"
min-sdk = "28"
target-sdk = "34"

[libraries]
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
coil = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "compose-material" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "compose-material3" }
compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "compose-navigation" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "compose" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
core = { group = "androidx.core", name = "core-ktx", version.ref = "core" }
core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "core-splashscreen" }
fuzzywuzzy = { group = "me.xdrop", name = "fuzzywuzzy", version.ref = "fuzzywuzzy" }
jaudiotagger = { group = "net.jthink", name = "jaudiotagger", version.ref = "jaudiotagger" }
lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime" }
media = { group = "androidx.media", name = "media", version.ref = "media" }
okhttp3 = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp3" }

[plugins]
android-app = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-gradle-plugin" }
