name: Code Analysis

on:
    push:
        branches-ignore:
            - site
            - gh-pages
            - i18n-summary
            - dependabot/**
        paths:
            - app/**
            - i18n/**
            - gradle/**
    pull_request_target:
        types:
            - opened
            - edited
        paths:
            - app/**
            - i18n/**
            - gradle/**
    workflow_dispatch:

permissions: {}

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event_name != 'pull_request_target' || github.event.pull_request.draft == false

        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive

            - uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: npm

            - uses: actions/setup-java@v4
              with:
                  distribution: zulu
                  java-version: 17
                  cache: gradle

            - name: ðŸš§ Do prerequisites
              run: npm ci

            - name: ðŸš¨ Analyze code
              run: |
                  npm run prebuild
                  chmod +x ./gradlew
                  ./gradlew lintRelease
