name: i18n Summary

on:
    push:
        branches:
            - main
        paths:
            - .phrasey/**
            - i18n/**
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                  node-version: "18.13.0"
                  cache: npm

            - name: ğŸ—ï¸  Prerequisites
              run: npm install

            - name: ğŸ”¨ Build
              run: npm run i18n:summary

            - name: ğŸš€ Push summary files
              uses: zyrouge/gh-push-action@v1.0.5
              with:
                  directory: phrasey-dist
                  branch: i18n-summary
